FTPOSError: removed any uses of the attribute ftp_exception. Because     FTPOSError wraps ftplib errors and we have an exception hierarchy,     there should no longer be a need to access the ftplib exception.