Add test for "missing" `mode` argument
This works because `FTPHost.open` sets `mode` to "r" by default. On
the other hand, passing `None` for the mode to `FTPFile._open`
causes a

  TypeError: argument of type 'NoneType' is not iterable

However, this isn't so relevant since clients should always use
`FTPHost.open`, not `FTPFile._open`.